[package]
name = "sensei"
version = "0.2.1"
edition = "2021"

[workspace]
members = [".", "entity", "migration", "senseicore"]

[[bin]] # Bin to run sensei cli
name = "senseicli"
path = "src/cli.rs"

[[bin]] # Bin to run sensei daemon
name = "senseid"
path = "src/main.rs"

[dependencies]
lightning = { version = "0.0.108", features = ["max_level_trace"] }
lightning-block-sync = { version = "0.0.108", features = [ "rpc-client" ] }
lightning-invoice = { version = "0.16.0" }
lightning-net-tokio = { version = "0.0.108" }
lightning-persister = { version = "0.0.108" }
lightning-background-processor = { version = "0.0.108" }
lightning-rapid-gossip-sync = { version = "0.0.108" }
base64 = "0.13.0"
bitcoin = "0.28.1"
bitcoin-bech32 = "0.12"
bech32 = "0.8"
futures = "0.3"
chrono = "0.4"
rand = "0.8.4"
axum = { version = "0.4.2", features = ["headers"] }
http = "0.2"
tower = { version = "0.4", features = ["full"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = { version = "1.0" }
tokio = { version = "1.17", features = [ "io-util", "macros", "rt", "rt-multi-thread", "sync", "net", "time" ] }
log = "0.4.16"
env_logger = "0.9.0"
bitcoincore-rpc = "0.15"
bdk = "0.19"
tonic = "0.7.2"
prost = "0.10"
pin-project = "1.0"
hyper = "0.14"
clap = { version = "3.0", features = [ "derive", "env" ] }
headers = "0.3"
tindercrypt = { version = "0.3.2", default-features = false }
uuid = { version = "0.8", features = ["serde", "v4"] }
macaroon = "0.2"
tower-http = { version = "0.2.5", features = ["fs", "trace", "cors"] }
tower-cookies = "0.4"
dirs = "4.0"
public-ip = "0.2"
rust-embed="6.3.0"
mime_guess = { version = "2" }
entity = { path = "entity" }
migration = { path = "migration" }
senseicore = { path = "senseicore" }

[build-dependencies]
tonic-build = "0.7.2"

[dev-dependencies]
serial_test = "0.6.0"
